[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
via_ir = true
remappings = [
    "account-abstraction/=lib/account-abstraction/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
taiko_mainnet = "${TAIKO_MAINNET_RPC_URL}"
taiko_hoodi = "${TAIKO_HOODI_RPC_URL}"
taiko_hekla = "${TAIKO_HEKLA_RPC_URL}"
