services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HEALTHCHECK_URL: http://localhost:3000/health
    volumes:
      - servo-data:/app/data

  bundler:
    build:
      context: .
      dockerfile: Dockerfile.bundler
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      HEALTHCHECK_URL: http://localhost:3001/health
    volumes:
      - servo-data:/app/data

volumes:
  servo-data:
